services:
  db:
    container_name: SplitBillApp
    image: postgres
    environment:
      POSTGRES_USER: SplitBill
      POSTGRES_PASSWORD: Password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5232:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: